apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: notary-harbor-tls
  namespace: harbor
spec:
  dnsNames:
  - notary.hbr.stateofk8s.com
  issuerRef:
    kind: Issuer
    name: harbor-issuer
  secretName: notary-harbor-tls
