apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/issuer: harbor-issuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
  name: notary-harbor
  namespace: default
spec:
  rules:
  - host: notary.hbr.stateofk8s.com
    http:
      paths:
      - backend:
          serviceName: harbor
          servicePort: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - notary.hbr.stateofk8s.com
    secretName: core-harbor-tls
